build: resolve missing includes showing on gcc-13
include/exmdbpp/exceptions.h:32:48: error: 'uint8_t' has not been declared
include/exmdbpp/exceptions.h:34:15: error: 'uint8_t' does not name a type
include/exmdbpp/exceptions.h:36:40: error: 'uint8_t' has not been declared
include/exmdbpp/ExmdbClient.h:92:25: error: 'const class exmdbpp::ExmdbProtocolError' has no member named 'code'
src/ExmdbClient.cpp:36:1: error: no declaration matches 'exmdbpp::ExmdbProtocolError::ExmdbProtocolError(const std::string&, uint8_t)'
src/ExmdbClient.cpp:40:13: error: no declaration matches 'std::string exmdbpp::ExmdbProtocolError::description(uint8_t)'